version: "3"
volumes:
  postgresql-data:
  redis-data:
  bundle:
  node_modules:

services:
  db:
    image: postgres:11.6
    ports:
      - '5432:5432'
    environment:
      POSTGRES_ROOT_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgresql-data:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    networks:
      - default
    ports:
      - '36380:6380'
    volumes:
      - redis-data:/var/lib/redis
  sub_mission:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3001:3001'
    links:
      - db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
      POSTGRES_HOST: db
      REDIS_URL: "redis://redis:6380"
    depends_on:
      - db
      - redis
    networks:
      - default
    volumes:
      - .:/sub_mission
      # https://qiita.com/shotat/items/57d049793605ffc20135
      - /sub_mission/log
      - /sub_mission/tmp
      - bundle:/usr/local/bundle
      - node_modules:/sub_mission/node_modules
    tty: true
    stdin_open: true
    # command: bundle exec rails server -b 0.0.0.0
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
