# -*- mode: dockerfile -*-
FROM ruby:2.4.0

RUN apt-get update -qq && \
    apt-get install -y build-essential \
                       libpq-dev \
                       nodejs

RUN mkdir /sub_mission

ENV APP_ROOT /sub_mission
WORKDIR $APP_ROOT

ADD ./Gemfile $APP_ROOT/Gemfile
ADD ./Gemfile.lock $APP_ROOT/Gemfile.lock

RUN gem install bundler
RUN bundle install --without production
ADD . $APP_ROOT
