default: &default
  adapter: postgresql
  encoding: unicode
  port: <%= ENV['POSTGRES_PORT'] %>
  host: <%= ENV['POSTGRES_HOST'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: 5

development:
  <<: *default
  database: sub_mission_dev

test:
  <<: *default
  database: sub_mission_test
